#footprint: [[0.1, 0.0], [0.0, 0.1], [0.0, -0.1], [-0.1, 0.0]]
robot_radius: 0.35

transform_tolerance: 0.5
update_frequency: 5.0
publish_frequency: 5.0

#must match incoming static map
global_frame: map
robot_base_frame: base_link
resolution: 0.05

rolling_window: false
track_unknown_space: true

plugins: 

    - {name: static,           type: "costmap_2d::StaticLayer"}            
    - {name: explore_boundary, type: "frontier_exploration::BoundedExploreLayer"}
    #Can disable sensor layer if gmapping is fast enough to update scans
    #- {name: sensor,           type: "costmap_2d::ObstacleLayer"}
    - {name: inflation,        type: "costmap_2d::InflationLayer"}

static:
    #Can pull data from gmapping, map_server or a non-rolling costmap            
    # might be slam_map_topic if we want to use that
    map_topic: hypermap_server/mapped_grid_map
    #move_base/global_costmap/costmap 
    # map_topic: move_base/global_costmap/costmap   
    subscribe_to_updates: false

explore_boundary:
    resize_to_boundary: false
    frontier_travel_point: centroid
    #set to false for gmapping, true if re-exploring a known area
    explore_clear_space: false

#sensor:
#    observation_sources: laser
#    laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true, raytrace_range: 4.0, obstacle_range: 4.0}

inflation:
    inflation_radius: 0.5
